# by Pavlo Bazilinskyy <pavlo.bazilinskyy@gmail.com>
import glob
import os

# Publications moved from /publications/<name> to the shorter /p/<name>. GitHub
# Pages cannot rewrite URLs, so every old page URL needs a real file that
# forwards. These stubs are generated, never edited: add a paper and the
# pre-commit hook writes its stub. Old asset URLs (.pdf, .jpg, .txt) cannot be
# stubbed this way and are caught by the fallback in 404.md instead.
SOURCE = '_publications/*.md'
STUB_DIR = 'publications'
NEW_PREFIX = '/p/'
MARKER = '<!-- generated by scripts/make_redirect_stubs.py -->'

TEMPLATE = """<!DOCTYPE html>
{marker}
<html lang="en">
<head>
<meta charset="utf-8">
<title>Redirecting to {target}</title>
<link rel="canonical" href="{target}">
<meta http-equiv="refresh" content="0; url={target}">
<meta name="robots" content="noindex">
</head>
<body>
<p>This page moved to <a href="{target}">{target}</a>.</p>
</body>
</html>
"""


def stub_for(name):
    """Build the redirect page for one publication.

    Args:
        name (string): Publication slug, e.g. alam2026automated.

    Returns:
        string: Complete HTML document.
    """
    return TEMPLATE.format(target=NEW_PREFIX + name, marker=MARKER)


def write_stubs(root):
    """Write one stub per publication and drop stubs with no publication left.

    Args:
        root (string): Repository root.

    Returns:
        tuple: (written, removed) counts.
    """
    out = os.path.join(root, STUB_DIR)
    # only ever clear our own output, never a hand-made file in the same folder
    if os.path.isdir(out):
        for f in os.listdir(out):
            path = os.path.join(out, f)
            if os.path.isfile(path) and MARKER in open(path, encoding='utf-8').read():
                os.remove(path)
    os.makedirs(out, exist_ok=True)
    names = [os.path.splitext(os.path.basename(p))[0]
             for p in sorted(glob.glob(os.path.join(root, SOURCE)))]
    for name in names:
        with open(os.path.join(out, name + '.html'), 'w', encoding='utf-8') as f:
            f.write(stub_for(name))
    # the listing moved to /p/ too, so the old directory needs its own forward
    with open(os.path.join(out, 'index.html'), 'w', encoding='utf-8') as f:
        f.write(TEMPLATE.format(target=NEW_PREFIX, marker=MARKER))
    return len(names)


def selftest():
    """Check the only part with any logic in it."""
    html = stub_for('alam2026automated')
    assert 'url=/p/alam2026automated"' in html, html
    assert 'rel="canonical" href="/p/alam2026automated"' in html
    assert MARKER in html, 'stub must be identifiable so a rerun can clean it up'
    assert 'noindex' in html, 'stubs must not compete with the real page'
    print('selftest ok')


if __name__ == '__main__':
    import sys
    if '--selftest' in sys.argv:
        selftest()
        sys.exit(0)
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    written = write_stubs(root)
    print('%d redirect stub(s) written to %s/.' % (written, STUB_DIR))
